### ISSUE TITLE
Create KK statics for exploration

### ISSUE THREAD

**Issue by caerfinon** [caerfinon/KerbinSideRemasteredTLA#3]
create 8 new KK statics to be explored underwater

Site Dives
- [x] 1 - Caged Twins (WLS)
- [x] 2 - Mammoth (WLS)
- [x] 3 - Carmen Caves (TLA)
- [x] 4 - Hatchery (TLA)
- [x] 5 - Hydrothermal Vent (TLA)
- [x] 6 - Tripod (TLA)
- [x] 7 - Avalon (TLA)
- [x] 8 - Coral Lagoon

**Comment by caerfinon** [comment]
v1.0.0 release includes Ker'Lyeh and the 2 from water launched sites (WLS)
Plan 7 more then episodic missions for each

**Comment by caerfinon** [comment]
8 sites completed. 


1 site withdrawn  - Ker'Lyeh
