### ISSUE TITLE
Create Misssion Code

### ISSUE THREAD

**Issue by caerfinon** [caerfinon/KerbinSideRemasteredTLA#5]
- [x] KUMA certification mission
- [x] KUMA General Exploration missions 
- [N] KUMA KK site missions
- [x] Deepsea Salvage missions
- [x] CG Patrol missions
- [x] CG Ship at Sea Rescue missions

**Comment by caerfinon** [comment]
Changed focus of missions for v1.0

**Comment by caerfinon** [comment]
KUMA KK static exploration missions part of upcoming release. Not in  v1.0.0
